# Generated by Django 3.1 on 2020-08-13 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa kategorii')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa instytucji')),
                ('description', models.CharField(max_length=128, verbose_name='Opis')),
                ('type', models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja porządkowa'), (3, 'Zbiórka lokalna')], default=1, verbose_name='Typ')),
                ('categories', models.ManyToManyField(to='app_in_good_hands.Category', verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Liczba worków')),
                ('address', models.CharField(max_length=128, verbose_name='Adres')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=128, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='Godzina odbioru')),
                ('pick_up_comment', models.CharField(max_length=254, verbose_name='Komentarz')),
                ('categories', models.ManyToManyField(to='app_in_good_hands.Category', verbose_name='Kategorie')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_in_good_hands.institution', verbose_name='Instytucja')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
